export const defaultAppTheme = {
  colors: {
    primary: "#F18484",
    secondary: "#FFAD60",
    tertiary: "#0D1729",
    primary_light: "#F89C90",
    secondary_light: "#FFEDDD",
    tertiary_light: "#11264E",
    failure: "#dc3545",
    success: "#198754",
    background: "#fff",
    white: "#fff",
    placeholder: "#cecece",
    gray_01: "#F4F4F4",
    gray_02: "#CBCCCE",
    gray_03: "#7C7C7C",
    gray_04: "#5D636C",
    gray_05: "#383D46",
  },
  fontSizes: {
    heading_h1: "24px",
    heading_h2: "20px",
    heading_h3: "18px",
    heading_h4: "16px",
    p1: "15px",
    p2: "14px",
    p3: "13px",
    p4: "12px",
    p5: "11px",
    p6: "9px",
  },
  fonts: {
    PoppinsRegular: "Poppins-Regular",
    PoppinsMedium: "Poppins-Medium",
    PoppinsSemiBold: "Poppins-SemiBold",
    PoppinsBold: "Poppins-Bold",
  },
  margins: {
    screenSideMargin: "25px",
  },
};
